version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: thebookstore-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: the-bookstore
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
